FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y g++ ccache openssl libssl-dev cmake gperf make git libreadline-dev zlib1g-dev

WORKDIR /
COPY . /td

WORKDIR /td
RUN mkdir build
WORKDIR build
RUN cmake ..
RUN make -j 2
